### ISSUE TITLE
Rebase/split #33

### ISSUE THREAD

**Issue by kolyshkin** [openshift/check-payload#68]
Unfortunately, #33 grew too big and was not merged before a major refactoring has taken place in #42. This issue is opened to track the progress of rebasing what was in #33 into multiple small PRs.

Here are the commits from #33 and their respective new PRs:

- [x] 2eb1908 feat: ensure the config is fully parsed (#53)
- [x] 90a7457 fix: print the entire configuration (#54, #71)
- [x] 856a827 Check for isGoExecutable errors (part of #56)
- [x] 869bc3e Refactor ExpectedSyms to return bool; document it (#57)
- [x] 62daf28 feat: add known errors (#86)
- [x] e43aa38 feat: ability to ignore individual errors (#86)
- [x] 2f335d6 Makefile: add verify-clean and verify-generate targets (#86)
- [x] 1196d62 fix: simplify getComponent and displayExceptions (#58, #59)
- [x] 8ff413c feat: print exceptions in new ignore_errors format (#86)
- [x] dbdb94d feat: show error name, component and tag in log (#69, XXX)
- [x] ~~96e69fd refactor: rm config.NodeScan~~
- [x] 8381d70 fix: nodeScan: rm nodeVersion (part of #75)
- [x] e37abb0 Rename node. ignores to rpm. ignores (part of #75)
- [x] ca19a03 fix: node_scan: log innerPath (part of #84)
- [x] 190f911 refactor: remove tag arg from validation functions (#60)
- [x] 720e1c7 refactor: scanBinary: rm component and tag args (part of #84)
- [x] dd05cb8 feat: print some stats (tracked by #89 now)
- [x] ~~02603bd feat: unify scan logic~~ (replaced by #87)

NB: commits that are crossed out are not going to be ported.

**Comment by kolyshkin** [comment]
With most of the stuff in (#53, #54, #56, #57, #58, #69, #75, #84, #86) and a couple of TODO items (#87, #89), this can finally be closed. Hooray 🔥 !

**Comment by kolyshkin** [comment]
In addition, `filepath.WalkDir` mode for node scan (which was the only mode in this PR) is now implemented by #103 (as well as rpm-based scan mode for payload scan).
